server:
  port: ${PORT:8080}

knowledge:
  path: knowledge

spring:
  config:
    import: optional:file:.env[.properties]

application:
  name: backend

ai:
  model:
    embedding: transformers
  embedding:
    transformer:
      onnx:
        model-uri: file:models/multilingual-e5-small/onnx/model.onnx

      tokenizer:
        uri: file:models/multilingual-e5-small/onnx/tokenizer.json
        options:
          padding: true


gemini:
  api-key: ${GEMINI_API_KEY}
  url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

embedding:
  index:
    path: models/embeddings.json

  lean-canvas:
    index:
      path: models/embeddings-lean-canvas.json

rag:
  search:
    top-k: 5
    min-similarity: 0.90
    context-score-window: 0.05
